const express = require("express")
const createAlbum = require("../controller/createAlbum")
const createArtist = require("../controller/createArtist")
const updateArtist = require("../controller/updateArtist")
const updateAlbum = require("../controller/updateAlbum")
const deleteAlbum = require("../controller/deleteAlbum")
const deleteArtist = require("../controller/deleteArtist")
const allAlbum = require("../controller/allAlbum")
const singleAlbum = require("../controller/singleAlbum")
const allArtist = require("../controller/allArtist")
const singleArtist = require("../controller/singleArtist")
const router = express.Router()

router.post("/createAlbum", createAlbum)
router.post("/createArtist", createArtist)
router.put("/updateArtist/:id", updateArtist)
router.put("/updateAlbum/:id", updateAlbum)
router.delete("/deleteAlbum/:id", deleteAlbum)
router.delete("/deleteArtist/:id", deleteArtist)
router.get("/allAlbum", allAlbum)
router.get("/allArtist", allArtist)
router.get("/singleAlbum/:id", singleAlbum)
router.get("/singleArtist/:id", singleArtist)

module.exports = router;